name: OK.ru Film Scraper

on:
  workflow_dispatch: # GitHub panelinden manuel çalıştırmak için
  # schedule:
  #   - cron: '0 0 * * *' # Her gece otomatik çalışmasını isterseniz başındaki # işaretlerini kaldırın

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Scraper'ı Çalıştır
        run: python scraper.py

      - name: Sonuçları Commit ve Push Yap
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "🤖 Filmler listesi ve M3U güncellendi" || exit 0
          git push
